# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: Code
tagline: Amelie Oller
description: >-
  My name is Amelie, I'm a Full-Stack Web Developer and I love code.
permalink: '/:title'
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
sidebar_home_link: true

# Author
author:
  name: Amelie Oller
  github: 'https://github.com/amelieoller'
  linkedin: 'https://www.linkedin.com/in/amelieoller/'

# Plugins
disqus:
  shortname: amelieoller
algolia:
  application_id: WH0DR124R6
  index_name: amelieoller
  search_only_api_key: 9deed4e992577accea6dc244cdcab480
